name: Publish Image to ECR Automatically

on:
  push:
    branches: ["main"]

env:
  APP_NAME: hextris
  ECS_CLUSTER: workshop-smkn1-jakarta
  ECS_SERVICE: hextris-app

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello World"

      - name: Print ENV
        run: echo "APP ENV = ${APP_NAME}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Check AWS CLI
        run: |
          aws --version

      - name: Upload to S3
        env:
          S3_BUCKET: ${{ secrets.BUCKET_NAME }}
        run: |
          aws s3 cp Dockerfile s3://$S3_BUCKET/Dockerfile

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: hextris
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker build -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: task-definition.json
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          force-new-deployment: true

      - name: Finish
        run: echo "Selesai menjalankan workflow."
